apiVersion: v1
kind: Service

metadata:
  name: spring-service

spec:
  type: NodePort
  selector:
    app: backend-app # deployment와 연결
  ports:
    - protocol: TCP
      port: 8080 # 서비스 포트
      targetPort: 8080 # pod 포트
      nodePort: 30000 # 컴퓨터 포트

